// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCexNSw2FNNITMSEjh0zNouj-ZolMNiGgw',
    appId: '1:251319478039:web:46aa26ae2a81b352f9b952',
    messagingSenderId: '251319478039',
    projectId: 'stoptheblues-365fd',
    authDomain: 'stoptheblues-365fd.firebaseapp.com',
    storageBucket: 'stoptheblues-365fd.appspot.com',
    measurementId: 'G-9CPGJJ7ETM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe984KQLOccwEHXnOwbOveCjpqaLl39Uo',
    appId: '1:251319478039:android:efe676ec45cd9a69f9b952',
    messagingSenderId: '251319478039',
    projectId: 'stoptheblues-365fd',
    storageBucket: 'stoptheblues-365fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-6oMFPs1vRbW0b9Fdq6bROaTLNs_ABf8',
    appId: '1:251319478039:ios:c6ecdae7428f83c3f9b952',
    messagingSenderId: '251319478039',
    projectId: 'stoptheblues-365fd',
    storageBucket: 'stoptheblues-365fd.appspot.com',
    iosBundleId: 'com.example.stoptheblues',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-6oMFPs1vRbW0b9Fdq6bROaTLNs_ABf8',
    appId: '1:251319478039:ios:3971dcd55637100bf9b952',
    messagingSenderId: '251319478039',
    projectId: 'stoptheblues-365fd',
    storageBucket: 'stoptheblues-365fd.appspot.com',
    iosBundleId: 'com.example.stoptheblues.RunnerTests',
  );
}
